print("Please enter a character for the eye")
eyes = input()
print("Beep's expression is now as follows:")
print("###########")
print(f"#   {eyes} {eyes}   #")
print("#   ---   #")
print("###########")